// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Space.AI
{
    using System;
    using System.Collections.Generic;
    
    
    public class CustomScript : ICustomScript
    {
        
        // The main execution loop of the NPC script
        public override void PerformLoop()
        {
        }
        
        // Triggered when an entity enters range
        public override void EnterRange(Data.UI.EntityObject entity)
        {
            UnityEngine.Vector2 vec2_3;
            vec2_3 = entity.Reference.position;
            bool result_2 = this.TurnTo(vec2_3);
        }
    }
}
