// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Space.AI
{
    using System;
    using System.Collections.Generic;
    
    
    public class CustomState : ICustomState
    {
        
        // The main execution loop of the NPC script
        public override void PerformLoop()
        {
            bool result_2;
            if ((0 == 0))
            {
                result_2 = true;
            }
            else
            {
                result_2 = false;
            }
            // While statement is comprised of a for loop with a boolean condition.
            for (
            ; result_2; 
            )
            {
            }
        }
    }
}
