// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Space.AI
{
    using System;
    using System.Collections.Generic;
    
    
    public class CustomScript : ICustomScript
    {
        
        // The main execution loop of the NPC script
        public override void PerformLoop()
        {
            string string_3 = "true";
            string string_4 = "false";
            if (false)
            {
UnityEngine.Debug.Log(string_3);
            }
            else
            {
UnityEngine.Debug.Log(string_4);
            }
        }
        
        // Triggered when an entity enters range
        public override void EnterRange(Data.UI.EntityObject entity)
        {
        }
    }
}
