// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Space.AI
{
    using System;
    using UnityEngine;
    using System.Collections.Generic;
    using Data.UI;
    
    
    public class CustomState : ICustomState
    {
        
        // The main execution loop of the NPC script
        public override void PerformLoop()
        {
            float number_2 = 0;
            float number_3 = 0;
            if ((number_2 == number_3))
            {
                // If condition is true, execute these statements.
            }
        }
    }
}
